name: Release
on:
  # I dont want to run this on every tag push for now
  # Also this prevents the workflow from accessing the gradle cache from other builds
  # which isnt the case with workflow_dispatch
  # read https://docs.github.com/en/actions/reference/workflows-and-actions/dependency-caching#restrictions-for-accessing-a-cache
  # push:
  #   tags:
  #     - '[0-9]+.[0-9]+.[0-9]+'
  #     - '[0-9]+.[0-9]+.[0-9]+-[a-zA-Z]+'
  workflow_dispatch:
    inputs:
      tag-name:
        type: string
        description: Release version, e.g. v1.2.3
        required: true
      cleanup:
        type: boolean
        description: Whether to remove existing releases related to tag
        default: false

        
env:
  PROJECT_NAME: "GeoInk"
  FLUTTER_VERSION: "3.44.9"
  APP_ID: "com.mahdigholamigodarzi.geoink"
  LINUX_DEPS: "libgtk-3-0 libgtk-3-dev libblkid1 liblzma5 build-essential"
  TAG: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') && github.ref_name || inputs.tag-name }}

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: false
          pub-cache: false 
          
      - name: Install deps
        run: | 
          sudo apt-get update && 
          sudo apt-get install -y ${{env.LINUX_DEPS}} xvfb

      - name: Test
        run:  xvfb-run -a flutter test integration_test/ -d linux

  pre-build:
    needs: integration_test
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.cleanup }}
    permissions: 
      contents: write
    runs-on:
      ubuntu-latest
    steps:
      - name: Delete Current Releases
        uses: 8Mi-Tech/delete-release-assets-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG }}
          deleteOnlyFromDrafts: false

  build:
    needs: pre-build
    if: ${{ always() && (needs.pre-build.result == 'success' || needs.pre-build.result == 'skipped') }}
    strategy:
      matrix:
        include:
          - platform: android
            os: ubuntu-latest
            artifact-extension: apk

          - platform: windows
            os: windows-latest
            arch: x64
            artifact-extension: zip

          - platform: linux
            os: ubuntu-latest
            arch: x64
            artifact-extension: gz,deb,appimage

    permissions: 
      contents: write

    name: Release
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: "stable"
          cache: false
          pub-cache: false 

      - name: Install Linux Dependencies
        if: matrix.platform == 'linux'
        run: | 
          sudo apt-get update && 
          sudo apt-get install -y ${{env.LINUX_DEPS}}

      - name: Install FastForge
        run: dart pub global activate fastforge

      - name: Setup FastForge PATH (Linux)
        if: matrix.platform == 'linux'
        run: echo "$HOME/.pub-cache/bin" >> "$GITHUB_PATH"

      - name: Cache Gradle
        uses: actions/cache@v6
        # cant access cache from other refs
        if: matrix.platform == 'android' && github.event_name == 'workflow_dispatch'
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Clean up disk space
        if: matrix.platform == 'android'
        run: |
          echo BEFORE CLEAN UP
          df -h
          echo "*************************************************************"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo apt-get autoremove -y
          sudo apt-get clean 
          echo "*************************************************************"
          echo AFTER CLEAN UP
          df -h

      - name: Pre Android Signing
        if: matrix.platform == 'android'
        run: |
          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 --decode > android/key.jks
          echo "storeFile=$(pwd)/android/key.jks" > android/key.properties
          echo "storePassword=${{ secrets.ANDROID_SIGNING_STORE_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}" >> android/key.properties

      - name: Install AppImage tool
        if: matrix.platform == 'linux'
        run: |
            wget -O appimagetool "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
            chmod +x appimagetool
            mv appimagetool /usr/local/bin/

      - name: Create Artifacts dir (linux)
        if: matrix.platform == 'linux' || matrix.platform == 'android'
        run: mkdir artifacts

      - name: Create Artifacts dir (Windows)
        if: matrix.platform == 'windows'
        shell: pwsh
        run: New-Item -ItemType Directory -Force -Path artifacts/
        
      
      # Build using FastForge
      - name: Release build 
        if: matrix.platform == 'windows'
        run: fastforge package --platform ${{matrix.platform}} --targets ${{matrix.artifact-extension}} --skip-clean
        
      - name: Prepare Windows artifact
        if: matrix.platform == 'windows'
        shell: pwsh
        run: |
          $zip = Get-ChildItem -Path "dist" -Filter "*.zip" -Recurse | Select-Object -First 1

          Move-Item `
            -Path $zip.FullName `
            -Destination "artifacts/${{ env.PROJECT_NAME }}-${{ matrix.platform }}-${{ env.TAG }}-${{ matrix.arch }}.zip" `
            -Force
      
      # all builds of apk
      - name: Android Release Build
        if: matrix.platform == 'android'
        run: |
          flutter build apk --release
          flutter build apk --split-per-abi --release

      - name: Prepare Android artifact
        if: matrix.platform == 'android'
        run: |
          ls -R ./build/app/outputs
          BASE_NAME="${{ env.PROJECT_NAME }}-${{ matrix.platform }}-${{ env.TAG }}"
          cp ./build/app/outputs/flutter-apk/*arm64-v8a*.apk artifacts/${BASE_NAME}-arm64.apk
          cp ./build/app/outputs/flutter-apk/*armeabi-v7a*.apk artifacts/${BASE_NAME}-arm7.apk
          cp ./build/app/outputs/flutter-apk/*x86_64*.apk artifacts/${BASE_NAME}-x86_64.apk
          cp ./build/app/outputs/flutter-apk/app-release.apk artifacts/${BASE_NAME}-universal.apk

      - name: Build Linux (Deb package)
        if: matrix.platform == 'linux'
        run: |
          fastforge package \
            --platform linux \
            --targets deb \
            --skip-clean

      - name: Prepare Linux artifact (Deb package)
        if: matrix.platform == 'linux'
        run: |
          cd dist/* && dpkg-deb -R *.deb deb-dir
          DESKTOP_FILE="deb-dir/usr/share/applications/geoink.desktop"
          sed -i "/^StartupWMClass.*$/d" $DESKTOP_FILE
          sed -i '/^\[Desktop Entry\]/a StartupWMClass=${{env.APP_ID}}' $DESKTOP_FILE
          rm -rf deb-dir/usr/share/icons/hicolor/*
          cp -r ../../assets/images/packaging/* deb-dir/usr/share/icons/hicolor/
          dpkg-deb -b deb-dir APP.deb
          mv APP.deb ../../artifacts/${{ env.PROJECT_NAME }}-${{ matrix.platform }}-${{ env.TAG }}-${{ matrix.arch }}.deb

      - name: Build Linux (GZip)
        if: matrix.platform == 'linux'
        run: flutter build linux --release

      - name: Prepare artifact (GZip)
        if: matrix.platform == 'linux'
        run: |
          DESTINATION_FOLDER="artifacts/${{ env.PROJECT_NAME }}"
          mkdir -p $DESTINATION_FOLDER
          cp assets/images/launcher_rounded.png $DESTINATION_FOLDER/${{ env.PROJECT_NAME }}.png
          cp -r build/linux/x64/release/bundle/* $DESTINATION_FOLDER
          tar -czf "artifacts/${{ env.PROJECT_NAME }}-${{ matrix.platform }}-${{ env.TAG }}-${{ matrix.arch }}.tar.gz" \
          -C artifacts/ ${{ env.PROJECT_NAME }}

      - name: Build Linux (AppImage)
        if: matrix.platform == 'linux'
        run: |
          fastforge package \
            --platform linux \
            --targets appimage \
            --skip-clean

      - name: Prepare artifact (AppImage)
        if: matrix.platform == 'linux'
        run: |
          cd dist/* && ./*.AppImage --appimage-extract > /dev/null
          sed -i "/^StartupWMClass.*$/d" squashfs-root/geoink.desktop
          sed -i '/^\[Desktop Entry\]/a StartupWMClass=${{env.APP_ID}}' "squashfs-root/geoink.desktop"
          find squashfs-root/usr/lib -name "libstdc++.so.6" -delete
          ARCH=x86_64 appimagetool --no-appstream squashfs-root APP.AppImage
          mv APP.AppImage ../../artifacts/${{ env.PROJECT_NAME }}-${{ matrix.platform }}-${{ env.TAG }}-${{ matrix.arch }}.AppImage


      - name: Draft release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: artifacts/*
          tag_name: ${{ env.TAG }}
          overwrite_files: true
          body_path: .github/release_template.md
          token: ${{ secrets.GITHUB_TOKEN }}